config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  devise_scope :user do
    post 'user/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: "posts#index"
  
  resources :users do
    member do
      get :following, :followers, :liked_posts
    end
  end
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :tags do
    get "posts", to: "posts#tag"
  end
  
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  mount_uploader :image, ImageUploader
  
  # ↓フォローモデル
  has_many :relationships
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :profile, length: { maximum: 200 }
  validates :email, presence: true, uniqueness: true, length: { minimum: 6 }, allow_blank: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, allow_blank: true

  def self.guest
    find_or_create_by(email: 'test@example.com') do |user|
      user.name = "testさん"
      user.profile = "よろしくお願いします。"
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end

  def after_update_path_for(resource)
    user_path(current_user)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    flash[:notice] = 'ゲストユーザーとしてログインしました。'
    redirect_to root_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order(created_at: "DESC")
  end

  def show
    @user  = User.find(params[:id])
    @posts = @user.posts.order(created_at: "DESC")
    @counts = @user.posts.count
    @likes = @user.likes.count
  end

  def liked_posts
    @user  = User.find(params[:id])
    @posts = @user.liked_posts
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/followers.html.haml
.album.py-4
  .container
    .row
      .col-lg-4.col-md-6.mb-3
        %h5 #{@user.name}のフォロワー一覧
    - @users.each do |user|
      .card.user.mb-4
        .card-body
          .row
            .col-sm-2
              .user-img-box
                - if user_signed_in? && current_user.image
                  = image_tag user.image.url, class: "user-img img-fliud"
                - else 
                  = image_tag "/assets/default.png", alt: "testuser", class: "user-img img-fliud"
            .col-sm-10
              .row
                .col-sm-12.col-md-12.py-1.border-bottom.border-secondary
                  = link_to (user.name), user_path(user.id)
              .row.no-gutters
                .col-sm-12.col-md-12.pt-1
                  = "#{user.profile}"
          .row
            .col-md-12.pt-1.card-text.d-flex.align-items-center.justify-content-between
              = render partial: 'relationships/follow'
            .col-md-12.pt-1.card-text
              = "投稿数 #{@counts}"
            .col-md-12.pt-1.card-text
              総いいね
              = @likes
            .col-sm-12.col-md-12
              - if user_signed_in? && current_user.id == @user.id && current_user.name != "testさん"
                = link_to "編集", edit_user_registration_path(@user.id)

app/views/users/following.html.haml
.album.py-4
  .container
    .row
      .col-lg-4.col-md-6.mb-3
        %h5 #{@user.name}のフォロー 一覧
    - @users.each do |user|
      .card.user.mb-4
        .card-body
          .row
            .col-sm-2
              .user-img-box
                - if user_signed_in? && current_user.image
                  = image_tag user.image.url, class: "user-img img-fliud"
                - else 
                  = image_tag "/assets/default.png", alt: "testuser", class: "user-img img-fliud"
            .col-sm-10
              .row
                .col-sm-12.col-md-12.py-1.border-bottom.border-secondary
                  = link_to (user.name), user_path(user.id)
              .row.no-gutters
                .col-sm-12.col-md-12.pt-1
                  = "#{user.profile}"
          .row
            .col-md-12.pt-1.card-text.d-flex.align-items-center.justify-content-between
              = render partial: 'relationships/follow'
            .col-md-12.pt-1.card-text
              = "投稿数 #{@counts}"
            .col-md-12.pt-1.card-text
              総いいね
              = @likes
            .col-sm-12.col-md-12
              - if user_signed_in? && current_user.id == @user.id && current_user.name != "testさん"
                = link_to "編集", edit_user_registration_path(@user.id)

app/views/users/index.html.haml
.album.py-4
  .container
    .row
      .col-lg-4.col-md-6.mb-3
        %h5 #{icon("fas", "users")} ユーザー 一覧
    - @users.each do |user|
      .card.user.mb-4
        .card-body
          .row
            .col-sm-2
              .user-img-box
                - if user.image?
                  = image_tag user.image.url, class: "user-img img-fliud"
                - else 
                  = image_tag "/assets/default.png", alt: "testuser", class: "user-img img-fliud"
            .col-sm-10
              .row
                .col-sm-12.col-md-12.py-1.border-bottom.border-secondary
                  = icon("fas", "user")
                  = link_to "#{user.name}", user_path(user.id) ,class: "name"
              .row.no-gutters
                .col-sm-12.col-md-12.pt-1
                  = "#{user.profile}"

app/views/users/liked_posts.html.haml
.album.py-4
  .container
    .row
      .col-lg-4.col-md-6.mb-3
        %h5 #{icon("fas", "heart")} いいね した一覧
    .row
      - @posts.each do |post|
        .col-lg-4.col-md-12.mb-3
          .card.shadow-sm
            - post.images.each do |image|
              .img-box
                = link_to (image_tag image.src.url), post_path(post.id), class: "img"
                = icon("fas", "external-link-alt", class: "search-icon")
              .col-md-12
                .card.py-2.mt-12
                  = link_to (post.title), post_path(post.id), class: "text"
                  .row
                    .col-sm-8.date
                      = icon("far", "clock")
                      = post.created_at.strftime("%Y-%m-%d %H:%M")
                    .col-sm-4.like
                      %div{:id => "likes_buttons_#{post.id}"}
                        = render partial: 'likes/like',locals: { post: post}
                  .tag
                    - if post.tags
                      - post.tags.each do |tag|
                        = link_to tag_posts_path(tag_id: tag.id), class: "tag mb-1, mr-1" do
                          = icon("fas", "tag")
                          = tag.name

app/views/users/show.html.haml
.album.py-4
  .container.post
    .row
      .col-lg-4.col-md-6.mb-3
        %h5 #{icon("fas", "user")} #{@user.name}のページ
    .card.user.mb-4
      .card-body
        .row
          .col-sm-2
            .user-img-box
              - if user_signed_in? && current_user
                = image_tag @user.image.url, class: "user-img img-fliud"
              - else 
                = image_tag "/assets/default.png", alt: "testuser", class: "user-img img-fliud"
          .col-sm-10
            .row
              .col-sm-12.col-md-12.py-1.border-bottom.border-secondary
                = icon("fas", "user")
                = @user.name
            .row.no-gutters
              .col-sm-12.col-md-12.pt-1
                = "#{@user.profile}"
        .row
          .col-md-12.pt-1.card-text.d-flex.align-items-center.justify-content-between
            = render partial: 'relationships/follow'
          .col-md-12.pt-1.card-text
            = "投稿数 #{@counts}"
          .col-md-12.pt-1.card-text
            総いいね
            = @likes
          .col-sm-12.col-md-12
            - if user_signed_in? && current_user.id == @user.id && current_user.name != "testさん"
              = link_to "編集", edit_user_registration_path(@user.id)
              

    .row
      - @posts.each do |post|
        .col-lg-4.col-md-12.mb-3
          .card.shadow-sm
            - post.images.each do |image|
              .img-box
                = link_to (image_tag image.src.url), post_path(post.id), class: "img"
                = icon("fas", "external-link-alt", class: "search-icon")
              .col-md-12
                .card.py-2.mt-12
                  = link_to (post.title), post_path(post.id), class: "text"
                  .row
                    .col-sm-8.date
                      = icon("far", "clock")
                      = post.created_at.strftime("%Y-%m-%d %H:%M")
                    .col-sm-4.like
                      %div{:id => "likes_buttons_#{post.id}"}
                        = render partial: 'likes/like',locals: { post: post}
                  .tag
                    - if post.tags
                      - post.tags.each do |tag|
                        = link_to tag_posts_path(tag_id: tag.id), class: "tag mb-1, mr-1" do
                          = icon("fas", "tag")
                          = tag.name