config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  devise_scope :user do
    post 'user/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: "posts#index"
  
  resources :users do
    member do
      get :following, :followers, :liked_posts
    end
  end
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :tags do
    get "posts", to: "posts#tag"
  end
  
  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  validates :title, presence: true, length: { maximum: 40 }
  validates :content, presence: true, length: { maximum: 300 }
  validates_associated :images
  validates :images, presence: true

  def self.search(search)
    if search
      Post.where('title LIKE(?) OR content LIKE(?) OR hashbody LIKE(?) ', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Post.all
    end
  end

  after_create do
    post = Post.find_by(id: id)
    hashtags = hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete("#＃"))
      post.tags << tag
    end
  end

  before_update do
    post = Post.find_by(id: id)
    post.tags.clear
    hashtags = hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete("#＃"))
      post.tags << tag
    end
  end

  def liked_by?(user)
    self.likes.where(user_id: user.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search, :tag]

  def index
    @posts = Post.includes([:images]).order(created_at: "DESC")
  end

  def new
    @post = Post.new
    @post.images.new
  end

  def create
    Post.create(post_params)
    flash[:notice] = "新規投稿しました。"
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    @tag = Tag.new
    @tags = @post.tags
    @user = User.new
    @image = @user.image
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:alertnow] = "投稿を削除しました。"
    redirect_to root_path
  end

  def search
    @post = Post.search(params[:keyword]).order(created_at: "DESC")
  end

  def tag
    @tag_list = Tag.includes([:name])
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts.all
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :hashbody, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_index.html.haml
.album.py-4
  .container
    .row
      - @post.each do |post|
        .col-lg-4.col-md-6.mb-3
          .card.shadow-sm
            - post.images.each do |image|
              .img-box
                = link_to (image_tag image.src.url), post_path(post.id), class: "img"
              .col-md-12
                .card.py-2.mt-12
                  = link_to (post.title), post_path(post.id), class: "text"
                  .row
                    .col-sm-8.date
                      = post.created_at.strftime("%Y-%m-%d %H:%M")
                    .col-sm-4.like
                      %div{:id => "likes_buttons_#{post.id}"}
                        = render partial: 'likes/like',locals: { post: post}
                  .tag
                    - if post.tags
                      - post.tags.each do |tag|
                        = link_to tag_posts_path(tag_id: tag.id), class: "tag mb-1, mr-1" do
                          = icon("fas", "hashtag")
                          = tag.name

app/views/posts/_newedit.html.haml
.account-wrapper
  .account-wrapper-inner
    .account-main
      %h2 新規投稿
      = form_with model: @post, local: true do |f|
        = f.label :タイトル
        %em 必須(40文字以内)
        %br/
        = f.text_field :title, class: "new-form"
        = f.label :コンテンツ
        %em 必須(300文字以内)
        %br/
        = f.text_area :content, row: "10", class: "new-form"
        = f.label :画像
        %em 必須
        %br/
        = f.fields_for :images do |i|
          = i.file_field :src, class: "new-form"
        = f.label :タグ
        %em 任意
        %br/
        = f.text_field :hashbody, placeholder: "例:#シャウエン,#景色", class: "new-form"
        %br/
        = f.submit "投稿する", class: "btn btn-primary"

app/views/posts/edit.html.haml
= render partial: 'posts/newedit',locals: { post: @post}

app/views/posts/index.html.haml
.container-fluid
  .row
    .col-xs-12.main-text
      %p モロッコの旅の思い出を共有しよう

-# = render partial: 'likes/like', collection: @post, as: "post" 

.album.py-4
  .container
    .row
      - @posts.each do |post|
        .col-lg-4.col-md-12.mb-3
          .card.shadow-sm
            - post.images.each do |image|
              .img-box
                = link_to (image_tag image.src.url), post_path(post.id), class: "img"
                = icon("fas", "external-link-alt", class: "search-icon")
              .col-md-12
                .card.py-2.mt-12
                  = link_to (post.title), post_path(post.id), class: "text"
                  .row
                    .col-sm-8.date
                      = icon("far", "clock")
                      = post.created_at.strftime("%Y-%m-%d %H:%M")
                    .col-sm-4.like
                      %div{:id => "likes_buttons_#{post.id}"}
                        = render partial: 'likes/like', locals: { post: post}
                  .tag
                    - if post.tags
                      - post.tags.each do |tag|
                        = link_to tag_posts_path(tag_id: tag.id), class: "tag mb-1, mr-1" do
                          = icon("fas", "tag")
                          = tag.name

app/views/posts/new.html.haml
= render partial: 'posts/newedit',locals: { post: @post}

app/views/posts/search.html.haml
= render partial: 'posts/index',locals: { post: @post}

app/views/posts/show.html.haml
.album.py-4
  .container
    .row
      .col-lg-12.col-md-12.mb-3
        .card.shadow-sm-2.show
          .img-box2
            - @post.images.each do |image|
              = image_tag image.src.url, class: "img2 img-fluid"
          .col-md-12.border-bottom.border-secondary
            .card.py-2.mt-12.show-title
              = @post.title
              .row
                .col-sm-8.date
                  = icon("far", "clock")
                  = @post.created_at.strftime("%Y-%m-%d %H:%M")
                .col-sm-4.like
                  %div{:id => "likes_buttons_#{@post.id}"}
                    = render partial: 'likes/like',locals: { post: @post}
              .tag
                - if @post.tags
                  - @post.tags.each do |tag|
                    = link_to tag_posts_path(tag_id: tag.id), class: "tag mb-1, mr-1" do
                      = icon("fas", "tag")
                      = tag.name
          .col-md-12.pt-2
            = image_tag @post.user.image.url, class: "user-img show"
            = link_to (@post.user.name), user_path(@post.user_id), class: "name"
          .col-md-12
            .card-text.pt-2.content
              = simple_format(@post.content)
          .col-md-12.text-right.edit
            - if user_signed_in? && current_user.id == @post.user_id
              = link_to "編集", edit_post_path(@post.id)
              = link_to "削除", post_path(@post.id), method: :delete

  .container
    .row
      .col-md-12
        .card.comments
          .card-text.pl-3.pb-2.border-bottom.border-secondary
            = icon("fas", "comments")
            コメント一覧
            %em (300文字以内)
          .comments
            - if @comments
              - @comments.each do |comment|
                .card-text-comments
                  .row
                    .col-sm-2.col-md-2
                      = image_tag comment.user.image.url, class: "user-img show"
                      = link_to (comment.user.name), user_path(comment.user_id), class: "name"
                    .col-sm-8.col-md-8.card-text
                      = simple_format(comment.text)
                    .col-sm-2.col-md-2
                      - if user_signed_in? && current_user.id == comment.user_id
                        = link_to "削除", post_comment_path(comment.post.id, comment.id), id: "comment_destroy", method: :delete

.fotter2.text-center.pb-4
  .container
    .row
      .col
        - if current_user
          = form_with(model: [@post, @comment], local: true, id: "new_comment") do |f|
            = f.text_area :text, placeholder: "コメント入力欄", rows: "2" , class: "textbox p-2"
            = f.submit "投稿する", class: "form__submit"
        - else
          = "*** コメントの投稿には新規登録/ログインが必要です ***"

app/views/posts/tag.html.haml
.album.py-4
  .container
    .row
      .col-lg-4.col-md-6.mb-3
        %h5 #{icon("fas", "tag")}#{@tag.name}の一覧
    .row
      - @posts.each do |post|
        .col-lg-4.col-md-6.mb-3
          .card.shadow-sm
            - post.images.each do |image|
              .img-box
                = link_to (image_tag image.src.url), post_path(post.id), class: "img"
                = icon("fas", "external-link-alt", class: "search-icon")
              .col-md-12
                .card.py-2.mt-12
                  = link_to (post.title), post_path(post.id), class: "text"
                  .row
                    .col-sm-8.date
                      = icon("far", "clock")
                      = post.created_at.strftime("%Y-%m-%d %H:%M")
                    .col-sm-4.like
                      = render partial: 'likes/like',locals: { post: post}
                  .tag
                    - if post.tags
                      - post.tags.each do |tag|
                        = link_to tag_posts_path(tag_id: tag.id), class: "tag mb-1, mr-1" do
                          = icon("fas", "tag")
                          = tag.name