config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  devise_scope :user do
    post 'user/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: "posts#index"
  
  resources :users do
    member do
      get :following, :followers, :liked_posts
    end
  end
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :tags do
    get "posts", to: "posts#tag"
  end
  
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true, length: { maximum: 300 }
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :post
  mount_uploader :src, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  validates :title, presence: true, length: { maximum: 40 }
  validates :content, presence: true, length: { maximum: 300 }
  validates_associated :images
  validates :images, presence: true

  def self.search(search)
    if search
      Post.where('title LIKE(?) OR content LIKE(?) OR hashbody LIKE(?) ', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Post.all
    end
  end

  after_create do
    post = Post.find_by(id: id)
    hashtags = hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete("#＃"))
      post.tags << tag
    end
  end

  before_update do
    post = Post.find_by(id: id)
    post.tags.clear
    hashtags = hashbody.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete("#＃"))
      post.tags << tag
    end
  end

  def liked_by?(user)
    self.likes.where(user_id: user.id).exists?
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :tag, optional: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  mount_uploader :image, ImageUploader
  
  # ↓フォローモデル
  has_many :relationships
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :profile, length: { maximum: 200 }
  validates :email, presence: true, uniqueness: true, length: { minimum: 6 }, allow_blank: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, allow_blank: true

  def self.guest
    find_or_create_by(email: 'test@example.com') do |user|
      user.name = "testさん"
      user.profile = "よろしくお願いします。"
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    Like.create(user_id: current_user.id, post_id: params[:post_id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search, :tag]

  def index
    @posts = Post.includes([:images]).order(created_at: "DESC")
  end

  def new
    @post = Post.new
    @post.images.new
  end

  def create
    Post.create(post_params)
    flash[:notice] = "新規投稿しました。"
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    @tag = Tag.new
    @tags = @post.tags
    @user = User.new
    @image = @user.image
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:alertnow] = "投稿を削除しました。"
    redirect_to root_path
  end

  def search
    @post = Post.search(params[:keyword]).order(created_at: "DESC")
  end

  def tag
    @tag_list = Tag.includes([:name])
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts.all
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :hashbody, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order(created_at: "DESC")
  end

  def show
    @user  = User.find(params[:id])
    @posts = @user.posts.order(created_at: "DESC")
    @counts = @user.posts.count
    @likes = @user.likes.count
  end

  def liked_posts
    @user  = User.find(params[:id])
    @posts = @user.liked_posts
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/_fotter.html.haml
.fotter.text-center
  .container
    .row
      .col
        %p.small.mb-0 ©2020 Morip

app/views/layouts/_header.html.haml
.navbar
  .container.d-flex
    .navbar-brand.d-flex.align-items-center
      = link_to image_tag("/assets/MORIP.png", class: "brand"), root_path, class: "header-brand"

.page-wrapper.chiller-theme
  %a#show-sidebar.btn.btn-sm.btn-dark{:href => "#"}
    %i.fas.fa-bars
  .toggled
  %nav#sidebar.sidebar-wrapper
    .sidebar-content
      .sidebar-brand
        %a{:href => root_path } Morip
        #close-sidebar
          %i.fas.fa-times
      - if user_signed_in?
        .sidebar-header
          .user-pic
            = image_tag current_user.image.url, class: "user-img img-fliud"
          .user-info
            %h6.user-name
              = current_user.name
            %span.user-role
              = link_to "マイページ", user_path(current_user)
            %span.user-role
              = link_to "ログアウト", destroy_user_session_path, method: :delete
        .sidebar-search
          %div
            .input-group
              = form_with(url: search_posts_path, local: true, method: :get, class: "form-inline") do |f|
                = f.text_field :keyword, placeholder: "Search", class: "form-control search-menu"
                = f.button :type => "submit", style: 'border-style: none;', class: "input-group-text" do
                  = icon("fas", "search")
        .sidebar-menu
          %ul
            %li.sidebar-menu
              %a{:href => new_post_path}
                %i.far.fa-image
                %span 新規投稿
            %li.sidebar-menu
              %a{:href => users_path}
                %i.fa.fa-users
                %span ユーザー 一覧
            %li.sidebar-menu
              %a{:href => liked_posts_user_path(current_user) }
                %i.fa.fa-heart
                %span いいね した一覧
            %li.sidebar-menu
              %a{:href => following_user_path(current_user) }
                %i.fa.fa-users
                %span フォロー中 一覧
            %li.sidebar-menu
              %a{:href => followers_user_path(current_user) }
                %i.fa.fa-users
                %span フォロワー 一覧
      - else
        .sidebar-search
          %div
            .input-group
              = form_with(url: search_posts_path, local: true, method: :get, class: "form-inline") do |f|
                = f.text_field :keyword, placeholder: "Search", class: "form-control search-menu"
                = f.button :type => "submit", style: 'border-style: none;', class: "input-group-text" do
                  = icon("fas", "search")
        .sidebar-menu
          %ul
            %li.sidebar-menu
              %a{:href => new_user_registration_path }
                %i.fas.fa-user-plus
                %span 新規登録
            %li.sidebar-menu
              %a{:href => new_user_session_path }
                %i.fa.fa-sign-in-alt
                %span ログイン
            %li.sidebar-menu.login
              = link_to "かんたんログイン", user_guest_sign_in_path, method: :post, class: "menu"
              = icon("fas", "user")

app/views/layouts/_notification.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MORIP
    %link{:href => "https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700", :rel => "stylesheet"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/notification'
    = yield
    = render 'layouts/fotter'